---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: staging
  domain: imgclass.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-0cd2e7dd81180ef1d
  image_type: m1.medium
  image_id: ami-20f71940
  security_groups:
  - default
  - web
  - web_tools
  zone: us-west-2b
  network: 
  gateway: 
  external_host: ec2-35-167-156-201.us-west-2.compute.amazonaws.com
  external_ip: 35.167.156.201
  internal_host: ip-172-31-38-69.us-west-2.compute.internal
  internal_ip: 172.31.38.69
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
  vpc: {}
