# ruby-build needs some extra packages to compile/install ruby runtimes
# curl is required.
# patch is required (for ree, some ruby head's).
# For JRuby (if you wish to use it) you will need:
#   aptitude install curl sun-java6-bin sun-java6-jre sun-java6-jdk
# For MRI & ree (if you wish to use it) you will need:
#   aptitude install curl bison build-essential zlib1g-dev libssl-dev libreadline5-dev libxml2-dev git-core
# For IronRuby (if you wish to use it) you will need:
#   aptitude install curl mono-2.0-devel

packages: [autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev]

# REQUIRED: The version of ruby-build to use for building ruby.
# It must be one of the versions from https://github.com/sstephenson/ruby-build/releases.
ruby_build_version: 20150413

# REQUIRED: Set to the version string for the ruby version you wish to use
# Run "ruby-build --definitions" to see the list of possible options or look through the list of
# recipes online at https://github.com/sstephenson/ruby-build/tree/master/share/ruby-build
ruby_version: 2.2.2

# REQUIRED: Installation path for ruby.
ruby_path: "/usr/local/rubies/#{ruby_version}"
